<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>vn.edufit</groupId>
    <artifactId>modules</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>verification</artifactId>
  <packaging>jar</packaging>
  <name>EduFit :: Module :: Verification</name>

  <dependencies>
    <!-- Nền tảng & Module liên kết -->
    <dependency>
      <groupId>vn.edufit</groupId>
      <artifactId>shared</artifactId>
    </dependency>
    <dependency>
      <groupId>vn.edufit</groupId>
      <artifactId>profile</artifactId>
    </dependency>
    <dependency>
      <groupId>vn.edufit</groupId>
      <artifactId>storage</artifactId>
    </dependency>
    <dependency>
      <groupId>vn.edufit</groupId>
      <artifactId>audit</artifactId>
    </dependency>

    <!-- Spring Starters -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webmvc</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
  </dependencies>

</project>
