-- =========================================================================
-- EduFit Database Migration V1.02: Module Profile & Subjects
-- =========================================================================

-- 1. BẢNG DANH MỤC CẤP HỌC (EDUCATION_LEVEL)
CREATE TABLE IF NOT EXISTS education_level (
    level_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(80) NOT NULL,
    sort_order  INT NOT NULL DEFAULT 0,
    is_active   BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT uk_education_level_name UNIQUE (name)
);

-- 2. BẢNG DANH MỤC MÔN HỌC (SUBJECT)
CREATE TABLE IF NOT EXISTS subject (
    subject_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT uk_subject_name UNIQUE (name)
);

-- 3. BẢNG HỒ SƠ HỌC VIÊN (STUDENT_PROFILE)
CREATE TABLE IF NOT EXISTS student_profile (
    student_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID NOT NULL,
    education_level_id  INT,
    area                VARCHAR(100),
    profile_complete    BOOLEAN NOT NULL DEFAULT false,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uk_student_profile_user UNIQUE (user_id),
    CONSTRAINT fk_student_profile_account FOREIGN KEY (user_id) REFERENCES account(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_student_profile_level FOREIGN KEY (education_level_id) REFERENCES education_level(level_id)
);

-- 4. BẢNG HỒ SƠ GIA SƯ (TUTOR_PROFILE)
CREATE TABLE IF NOT EXISTS tutor_profile (
    tutor_id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID NOT NULL,
    display_name        VARCHAR(100) NOT NULL,
    headline            VARCHAR(200),
    bio                 TEXT,
    teaching_mode       VARCHAR(20) NOT NULL,
    area                VARCHAR(100),
    price_per_session   BIGINT NOT NULL,
    experience_years    SMALLINT,
    teaching_method     TEXT,
    status              VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    verified_at         TIMESTAMPTZ,
    rating_avg          DECIMAL(3,2),
    review_count        INT NOT NULL DEFAULT 0,
    version             INT NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uk_tutor_profile_user UNIQUE (user_id),
    CONSTRAINT fk_tutor_profile_account FOREIGN KEY (user_id) REFERENCES account(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_tutor_mode CHECK (teaching_mode IN ('ONLINE', 'OFFLINE', 'BOTH')),
    CONSTRAINT chk_tutor_status CHECK (status IN ('DRAFT', 'UNVERIFIED', 'PENDING_VERIFICATION', 'VERIFIED'))
);

CREATE INDEX IF NOT EXISTS idx_tutor_profile_status ON tutor_profile (status);
CREATE INDEX IF NOT EXISTS idx_tutor_profile_rating ON tutor_profile (rating_avg);

-- 5. BẢNG MÔN HỌC GIA SƯ GIẢNG DẠY (TUTOR_SUBJECT)
CREATE TABLE IF NOT EXISTS tutor_subject (
    tutor_subject_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tutor_id            UUID NOT NULL,
    subject_id          INT NOT NULL,
    education_level_id  INT NOT NULL,

    CONSTRAINT uk_tutor_subject UNIQUE (tutor_id, subject_id, education_level_id),
    CONSTRAINT fk_tutor_subject_tutor FOREIGN KEY (tutor_id) REFERENCES tutor_profile(tutor_id) ON DELETE CASCADE,
    CONSTRAINT fk_tutor_subject_subject FOREIGN KEY (subject_id) REFERENCES subject(subject_id),
    CONSTRAINT fk_tutor_subject_level FOREIGN KEY (education_level_id) REFERENCES education_level(level_id)
);

-- 6. BẢNG KHUNG GIỜ RẢNH CỦA GIA SƯ (TUTOR_AVAILABILITY_SLOT)
CREATE TABLE IF NOT EXISTS tutor_availability_slot (
    slot_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tutor_id    UUID NOT NULL,
    day_of_week SMALLINT NOT NULL,
    start_time  TIME NOT NULL,
    end_time    TIME NOT NULL,

    CONSTRAINT fk_tutor_slot_tutor FOREIGN KEY (tutor_id) REFERENCES tutor_profile(tutor_id) ON DELETE CASCADE,
    CONSTRAINT chk_tutor_day CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT chk_slot_t CHECK (end_time > start_time)
);

CREATE INDEX IF NOT EXISTS idx_tutor_slot_day ON tutor_availability_slot (tutor_id, day_of_week);

-- 7. BẢNG MỤC TIÊU HỌC TẬP (LEARNING_GOAL)
CREATE TABLE IF NOT EXISTS learning_goal (
    goal_id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id      UUID NOT NULL,
    subject_id      INT NOT NULL,
    current_level   SMALLINT NOT NULL,
    desired_level   SMALLINT NOT NULL,
    goal_type       VARCHAR(30) NOT NULL,
    deadline        DATE NOT NULL,
    mode            VARCHAR(20) NOT NULL,
    area            VARCHAR(100),
    budget_min      BIGINT,
    budget_max      BIGINT NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_learning_goal_student FOREIGN KEY (student_id) REFERENCES student_profile(student_id) ON DELETE CASCADE,
    CONSTRAINT fk_learning_goal_subject FOREIGN KEY (subject_id) REFERENCES subject(subject_id),
    CONSTRAINT chk_goal_levels CHECK (desired_level > current_level),
    CONSTRAINT chk_goal_type CHECK (goal_type IN ('CONSOLIDATE', 'IMPROVE_GRADES', 'ADVANCED_STUDY', 'EXAM_PREPARATION', 'OTHER')),
    CONSTRAINT chk_goal_mode CHECK (mode IN ('ONLINE', 'OFFLINE', 'BOTH')),
    CONSTRAINT chk_goal_status CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE INDEX IF NOT EXISTS idx_learning_goal_student ON learning_goal (student_id, status);

-- 8. BẢNG KHUNG GIỜ CẦN HỌC (GOAL_AVAILABILITY_SLOT)
CREATE TABLE IF NOT EXISTS goal_availability_slot (
    slot_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    goal_id     UUID NOT NULL,
    day_of_week SMALLINT NOT NULL,
    start_time  TIME NOT NULL,
    end_time    TIME NOT NULL,

    CONSTRAINT fk_goal_slot_goal FOREIGN KEY (goal_id) REFERENCES learning_goal(goal_id) ON DELETE CASCADE,
    CONSTRAINT chk_goal_day CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT chk_slot_g CHECK (end_time > start_time)
);
