<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>vn.edufit</groupId>
    <artifactId>platform</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>storage</artifactId>
  <packaging>jar</packaging>
  <name>EduFit :: Platform :: File Storage</name>


  <dependencies>
    <dependency>
      <groupId>vn.edufit</groupId>
      <artifactId>shared</artifactId>
    </dependency>
    <!-- Apache Tika phân tích Magic Bytes chống tấn công upload mã độc (NFR-08) -->
    <dependency>
      <groupId>org.apache.tika</groupId>
      <artifactId>tika-core</artifactId>
    </dependency>
    <!-- Cần Spring Web Context để thao tác MultipartFile -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
    </dependency>
  </dependencies>



</project>
